trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - uf850_controller
    - xarm5_controller
    - rg6_controller
    - xarm_gripper_controller
    - slider_controller

  uf850_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - uf850_joint1
      - uf850_joint2
      - uf850_joint3
      - uf850_joint4
      - uf850_joint5
      - uf850_joint6

  xarm5_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - xarm5_joint1
      - xarm5_joint2
      - xarm5_joint3
      - xarm5_joint4
      - xarm5_joint5

  rg6_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rg6_right_drive_joint

  xarm_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - xarm_gripper_right_drive_joint

  slider_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - uf_slide_joint
