"""YAML import/export and JSON project save/load for device configs."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

import yaml


def load_yaml(path: str | Path) -> Dict[str, Any]:
    with Path(path).open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ValueError("Top-level YAML document must be a mapping.")
    return data


def save_yaml(path: str | Path, data: Dict[str, Any]) -> None:
    """Export config as spec-format YAML with header comment."""
    device = data.get("device", {})
    dev_class = device.get("class") or device.get("device_class", "")
    dev_model = device.get("model") or device.get("device_model", "")
    now = datetime.now().isoformat(timespec="seconds")

    header = (
        f"# Device Configuration: {dev_class} / {dev_model}\n"
        f"# Generated by Device Config Builder\n"
        f"# Date: {now}\n\n"
    )

    with Path(path).open("w", encoding="utf-8") as handle:
        handle.write(header)
        yaml.safe_dump(data, handle, sort_keys=False, allow_unicode=False, default_flow_style=False)


def save_project(path: str | Path, data: Dict[str, Any]) -> None:
    """Save full project data as JSON (round-trip fidelity)."""
    with Path(path).open("w", encoding="utf-8") as handle:
        json.dump(data, handle, indent=2, ensure_ascii=False)


def load_project(path: str | Path) -> Dict[str, Any]:
    """Load a JSON project file."""
    with Path(path).open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError("Top-level JSON document must be a mapping.")
    return data
